---
title: "Statistical Learning - Chapter 2 (Applied Exercises)"
output: html_document
---

```{r 8a}
college = read.csv("data/College.csv", header=T, na.strings="?")

```


```{r 8b}
rownames(college) = college [,1]  ## use first column as row names
fix(college)

college = college[,-1]  ## eliminate first column
fix(college)

```

```{r 8c}
summary(college)
pairs(college[,1:10])

plot(college$Private, college$Outstate)

Elite = rep("No", nrow(college))
Elite[college$Top10perc > 50] = "Yes"
Elite = as.factor(Elite)
college = data.frame(college, Elite)
summary(college)
plot(college$Elite, college$Outstate)

par(mfrow=c(2,2))
hist(college$Enroll, col=2, breaks=10)
hist(college$Personal, col=2, breaks=10)
hist(college$Expend, col=2, breaks=10)
hist(college$Grad.Rate, col=2, breaks=10)


```


```{r 9a}
auto = read.csv("data/Auto.csv", header=T, na.strings="?")
summary(auto)

# Quantitative predictors: mpg, displacement, horsepower, weight, acceleration.
# Qualitative predictors: cylinders, year, origin, name.

```

```{r 9b}
range(auto[, "mpg"])
range(auto[, "displacement"])
range(auto[, "horsepower"], na.rm=TRUE)
range(auto[, "weight"])
range(auto[, "acceleration"])

# Same result but using lapply:
quantPredictors = c("mpg", "displacement", "horsepower", "weight", "acceleration")
lapply(auto[, quantPredictors], range, na.rm=TRUE)


```

```{r 9c}
lapply(auto[, quantPredictors], mean, na.rm=TRUE)
lapply(auto[, quantPredictors], sd, na.rm=TRUE)

```

```{r 9d}
autoSubset = auto[-(10:85), ]
lapply(autoSubset[, quantPredictors], range, na.rm=TRUE)
lapply(autoSubset[, quantPredictors], mean, na.rm=TRUE)
lapply(autoSubset[, quantPredictors], sd, na.rm=TRUE)

```


```{r 9e-9f}
pairs(auto)

auto$cylinders = as.factor(auto$cylinders)
auto$year      = as.factor(auto$year)
auto$origin    = as.factor(auto$origin)

par(mfrow=c(1,3))
plot(auto$cylinders, auto$mpg)
plot(auto$year, auto$mpg)
plot(auto$origin, auto$mpg)

```


```{r 10a}
library (MASS)
#fix(Boston)
?Boston
dim(Boston)

```


```{r 10b}
pairs(Boston)
pairs(~ crim + nox + rm + age + dis + black + lstat + medv , data = Boston)

```


```{r 10d}
predictors = c("zn", "indus", "nox", "rm", "age", "dis", "rad", "tax", "ptratio", "black", "lstat", "medv")
lapply(Boston[, predictors], range, na.rm=TRUE)
lapply(Boston[, predictors], mean, na.rm=TRUE)


```


```{r 10e}
nrow(Boston[Boston$chas == 1,])

```


```{r 10f}
median(Boston$ptratio)

```


```{r 10g}
min(Boston$medv)
Boston[Boston$medv == min(Boston$medv), ]

```


```{r 10h}
nrow(Boston[Boston$rm > 7, ])
nrow(Boston[Boston$rm > 8, ])
Boston[Boston$rm > 8, ]

```















